apiVersion: v1
kind: ReplicationController
metadata:
  name: elasticsearch-logging
  namespace: kube-system
spec:
  replicas: 2
  selector:
    k8s-app: elasticsearch-logging
    version: v1
  template:
    metadata:
      labels:
        k8s-app: elasticsearch-logging
        version: v1
    spec:
      containers:
      - image: gcr.io/google-containers/elasticsearch:v2.4.1
        imagePullPolicy: IfNotPresent
        name: elasticsearch-logging
        ports:
        - containerPort: 9200
          name: db
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: 100m
        volumeMounts:
        - mountPath: /data
          name: es-persistent-storage
      volumes:
      - emptyDir: {}
        name: es-persistent-storage
